sudo: false

language: cpp

compiler: gcc

dist: trusty

before_install:
# C++17
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- pip install --user cpp-coveralls

install:
# C++17
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

addons:
  sonarcloud:
    organization: "wlchs-github" # the key of the org you chose at step #3
    token:
    - ${SONAR_TOKEN}

script:
- cmake -H. -Bbuild
- sonar-scanner
- cd build
- cmake --build .
- ctest

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" --exclude build/googletest --exclude sudooku_tests

notifications:
  email: false